name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build project
      run: xcodebuild -project CicdDemo.xcodeproj -scheme CicdDemo -destination "platform=iOS Simulator,name=iPhone 15" build

    - name: Run tests
      run: xcodebuild -project CicdDemo.xcodeproj -scheme CicdDemo -destination "platform=iOS Simulator,name=iPhone 15" test
